### ISSUE TITLE
Not compatible with Silverstripe 4

### ISSUE THREAD

**Issue by tungdt-90** [axllent/silverstripe-tiled-gridfield#3]
Hi,

I would like to know, is there any chance that this module will be updated to work with Silverstripe 4 ?

**Comment by axllent** [comment]
Hi. Yes definitely, I just haven't gotten to upgrading this module yet.

**Comment by tungdt-90** [comment]
I'm so glad to know. I really like your module, and I use it in every projects.

Have a good day !

**Comment by axllent** [comment]
I've just released a new version for SilverStripe 4.
